<?xml version="1.0" encoding="windows-1251"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by VI (GNIVC FNS RF) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:sch="http://purl.oclc.org/dsdl/schematron" xmlns:usch="http://www.unisoftware.ru/schematron-extensions" xmlns:sql="urn:schemas-microsoft-com:mapping-schema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Файл">
		<xs:annotation>
			<!---**************************************************************************************************************************************************************************-->
			<xs:appinfo>
				<sch:pattern name="Проверка имени файла на соответствие значению атрибута @ИдФайл">
					<sch:rule context="Файл">
						<sch:assert test="usch:getFileName() = @ИдФайл">
							<usch:error code="0400400007" path="@ИдФайл" value-of-select="@ИдФайл" doc-id-path="usch:getFileName()" doc-id-caption="Файл">Имя файла обмена "<usch:value-of select="usch:getFileName()"/>" не совпадает со значением элемента ИдФайл "<usch:value-of select="@ИдФайл"/>"</usch:error>
						</sch:assert>
					</sch:rule>
				</sch:pattern>
			</xs:appinfo>
			<!---**************************************************************************************************************************************************************************-->
			<xs:documentation>Файл обмена</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ИдПолИной" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Идентификатор иного получателя файла обмена информации грузоотправителя об изменении сведений о грузополучателе и (или) порте назначения</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="4"/>
							<xs:maxLength value="46"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Документ">
					<xs:annotation>
						<xs:documentation>Электронная транспортная накладная, информация грузоотправителя об изменении сведений о грузополучателе и (или) порте назначения</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ИдИнфГО">
								<xs:annotation>
									<xs:documentation>Идентификатор файла обмена информации грузоотправителя</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="ИдФайлИнфГО" use="required">
										<xs:annotation>
											<xs:documentation>Идентификатор файла обмена (информации грузоотправителя)</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1"/>
												<xs:maxLength value="255"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="ДатФайлИнфГО" type="ДатаТип" use="required">
										<xs:annotation>
											<xs:documentation>Дата формирования файла обмена информации грузоотправителя</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="ВрФайлИнфГО" type="ВремяТип" use="required">
										<xs:annotation>
											<xs:documentation>Время формирования файла обмена информации грузоотправителя</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="ЭП" use="required">
										<xs:annotation>
											<xs:documentation>Электронная подпись файла обмена информации грузоотправителя</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="СодИнфИзм">
								<xs:annotation>
									<xs:documentation>Содержание электронной транспортной накладной, информация грузоотправителя об изменении сведений о грузополучателе и (или) порте назначения</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ОтметИзм" maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>Сведения об отметках изменений</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:choice>
														<xs:element name="СвНовГП" type="УчастникТип">
															<xs:annotation>
																<xs:documentation>Сведения о грузополучателе</xs:documentation>
															</xs:annotation>
														</xs:element>
														<xs:element name="ПортНовНазнач" type="ПортТип">
															<xs:annotation>
																<xs:documentation>Сведения об изменении порта назначения</xs:documentation>
															</xs:annotation>
														</xs:element>
													</xs:choice>
													<xs:element name="ИнфПол" type="ИнфПолТип" minOccurs="0" maxOccurs="unbounded">
														<xs:annotation>
															<xs:documentation>Информационное поле</xs:documentation>
														</xs:annotation>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="ДатВрОтмет" type="ДатаВремяВЗТип" use="required">
													<xs:annotation>
														<xs:documentation>Дата и время отметки</xs:documentation>
													</xs:annotation>
												</xs:attribute>
												<xs:attribute name="ОбстОтмет" use="required">
													<xs:annotation>
														<xs:documentation>Описание обстоятельств, послуживших основанием для отметки</xs:documentation>
													</xs:annotation>
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="1"/>
															<xs:maxLength value="255"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
										<xs:element name="ИнфПол" type="ИнфПолТип" minOccurs="0" maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>Информационное поле</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="УИД_ТрН" use="required">
										<xs:annotation>
											<xs:documentation>Уникальный идентификатор документа (УИД) электронной транспортной накладной</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1"/>
												<xs:maxLength value="36"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="ДатВрИзм" type="ДатаВремяВЗТип" use="required">
										<xs:annotation>
											<xs:documentation>Дата и время изменений</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="ПодпИнфИзм" type="ПодписантТип">
								<xs:annotation>
									<!---*************************************************************************************************************************************************************-->
									<xs:appinfo>
										<sch:pattern name="Наличие элемента СвДоверЭл в зависимости от значения элемента СпосПодтПолном">
											<sch:rule context="ПодпИнфИзм">
												<sch:assert test="usch:iif( 
						@СпосПодтПолном=3  ,
						count(СвДоверЭл)!=0  , 
						count(СвДоверЭл)=0 
						)">
													<usch:error code="0400400007" path="СвДоверЭл" value-of-select="count(СвДоверЭл)"> Не выполнено условие присутствия (отсутствия) элемента СвДоверЭл при при значении элемента СпосПодтПолном, равном "<usch:value-of select="@СпосПодтПолном"/>". </usch:error>
												</sch:assert>
											</sch:rule>
										</sch:pattern>
									</xs:appinfo>
									<!---*************************************************************************************************************************************************************-->
									<!---*************************************************************************************************************************************************************-->
									<xs:appinfo>
										<sch:pattern name="Наличие элемента СвДоверБум в зависимости от значения элемента СпосПодтПолном">
											<sch:rule context="ПодпИнфИзм">
												<sch:assert test="usch:iif( 
						@СпосПодтПолном=5  ,
						count(СвДоверБум)!=0  , 
						count(СвДоверБум)=0 
						)">
													<usch:error code="0400400007" path="СвДоверБум" value-of-select="count(СвДоверБум)"> Не выполнено условие присутствия (отсутствия) элемента СвДоверБум при при значении элемента СпосПодтПолном, равном "<usch:value-of select="@СпосПодтПолном"/>". </usch:error>
												</sch:assert>
											</sch:rule>
										</sch:pattern>
									</xs:appinfo>
									<!---*************************************************************************************************************************************************************-->
									<xs:documentation>Сведения о лице, подписывающем файл обмена информации грузоотправителя об изменении сведений о грузополучателе и (или) порте назначения</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="КНД" use="required">
							<xs:annotation>
								<xs:documentation>Код формы документа по классификатору налоговых документов (КНД)</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="КНДТип">
									<xs:enumeration value="1110432"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="ПоСодИнфФайл" use="required">
							<xs:annotation>
								<xs:documentation>Наименование документа по содержанию информации в файле обмена информации грузоотправителя об изменении сведений о грузополучателе и (или) порте назначения</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="1"/>
									<xs:maxLength value="255"/>
									<xs:enumeration value="электронная транспортная накладная, информация грузоотправителя об изменении сведений о грузополучателе и (или) порте назначения"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="ДатаИнфИзм" type="ДатаТип" use="required">
							<xs:annotation>
								<xs:documentation>Дата формирования файла обмена информации грузоотправителя об изменении сведений о грузополучателе и (или) порте назначения</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="ВрИнфИзм" type="ВремяТип" use="required">
							<xs:annotation>
								<xs:documentation>Время формирования файла обмена информации грузоотправителя об изменении сведений о грузополучателе и (или) порте назначения</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="ИдФайл" use="required">
				<xs:annotation>
					<xs:documentation>Идентификатор файла</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ВерсПрог" use="required">
				<xs:annotation>
					<xs:documentation>Версия программы, с помощью которой сформирован файл</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="40"/>
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ВерсФорм" use="required">
				<xs:annotation>
					<xs:documentation>Версия формата</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="5"/>
						<xs:enumeration value="5.01"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="УчастникТип">
		<xs:annotation>
			<xs:documentation>Сведения об участнике факта хозяйственной жизни</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="ИдСв">
				<xs:annotation>
					<xs:documentation>Идентификационные сведения</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:choice>
						<xs:element name="СвИП">
							<xs:annotation>
								<xs:documentation>Сведения об индивидуальном предпринимателе</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="ФИО" type="ФИОТип">
										<xs:annotation>
											<xs:documentation>Фамилия, имя, отчество (при наличии)</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="ИННФЛ" type="ИННФЛТип" use="required">
									<xs:annotation>
										<xs:documentation>Идентификационный номер налогоплательщика (ИНН) физического лица</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="СвГосРегИП" use="optional">
									<xs:annotation>
										<xs:documentation>Реквизиты свидетельства о государственной регистрации индивидуального предпринимателя</xs:documentation>
									</xs:annotation>
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:minLength value="1"/>
											<xs:maxLength value="100"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="ОГРНИП" type="ОГРНИПТип" use="optional">
									<xs:annotation>
										<xs:documentation>Основной государственный регистрационный номер индивидуального предпринимателя</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="ДатаОГРНИП" type="ДатаТип" use="optional">
									<xs:annotation>
										<xs:documentation>Дата присвоения основного государственного регистрационного номера индивидуального предпринимателя</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="ИныеСвед" use="optional">
									<xs:annotation>
										<xs:documentation>Иные сведения, идентифицирующие физическое лицо</xs:documentation>
									</xs:annotation>
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:minLength value="1"/>
											<xs:maxLength value="255"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
						<xs:element name="СвЮЛУч">
							<xs:annotation>
								<xs:documentation>Сведения об организации, состоящей на учете в налоговом органе</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:attribute name="НаимОрг" use="required">
									<xs:annotation>
										<xs:documentation>Полное наименование</xs:documentation>
									</xs:annotation>
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:minLength value="1"/>
											<xs:maxLength value="1000"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="ИННЮЛ" type="ИННЮЛТип" use="required">
									<xs:annotation>
										<xs:documentation>ИНН юридического лица</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="КПП" type="КППТип" use="required">
									<xs:annotation>
										<xs:documentation>Код причины постановки на учет (КПП)</xs:documentation>
									</xs:annotation>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
						<xs:element name="СвИнНеУч" type="СвИнНеУчТип">
							<xs:annotation>
								<!---*************************************************************************************************************************************************************-->
								<xs:appinfo>
									<sch:pattern name="Наличие элемента Идентиф в зависимости от наличия элемента ИныеСвед">
										<sch:rule context="СвИнНеУч">
											<sch:assert test="usch:iif( 
						count(@ИныеСвед)=0 ,
						count(@Идентиф)!=0  , 
						( count(@Идентиф)!=0  or  count(@Идентиф)=0 ) 
						)">
												<usch:error code="0400400007" path="@Идентиф" value-of-select="count(@Идентиф)"> Не выполнено условие присутствия (отсутствия) элемента Идентиф при наличии элемента  ИныеСвед в количестве, равном "<usch:value-of select="count(@ИныеСвед)"/>". </usch:error>
											</sch:assert>
										</sch:rule>
									</sch:pattern>
								</xs:appinfo>
								<!---*************************************************************************************************************************************************************-->
								<!---*************************************************************************************************************************************************************-->
								<xs:appinfo>
									<sch:pattern name="Наличие элемента ИныеСвед в зависимости от наличия элемента Идентиф">
										<sch:rule context="СвИнНеУч">
											<sch:assert test="usch:iif( 
						count(@Идентиф)=0 ,
						count(@ИныеСвед)!=0  , 
						( count(@ИныеСвед)!=0  or  count(@ИныеСвед)=0 ) 
						)">
												<usch:error code="0400400007" path="@ИныеСвед" value-of-select="count(@ИныеСвед)"> Не выполнено условие присутствия (отсутствия) элемента ИныеСвед при наличии элемента Идентиф в количестве, равном "<usch:value-of select="count(@Идентиф)"/>". </usch:error>
											</sch:assert>
										</sch:rule>
									</sch:pattern>
								</xs:appinfo>
								<!---*************************************************************************************************************************************************************-->
								<xs:documentation>Сведения об иностранной организации (иностранном гражданине), не состоящей/состоящем на учете в налоговом органе</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="СвФЛУч">
							<xs:annotation>
								<!---*************************************************************************************************************************************************************-->
								<xs:appinfo>
									<sch:pattern name="Наличие элемента ФИО в зависимости от наличия элементов ИННФЛ и ИныеСвед">
										<sch:rule context="СвФЛУч">
											<sch:assert test="usch:iif( 
						count(@ИННФЛ)=0 and count(@ИныеСвед)=0  ,
						count(ФИО)!=0  , 
						( count(ФИО)!=0  or  count(ФИО)=0 ) 
						)">
												<usch:error code="0400400007" path="ФИО" value-of-select="count(ФИО)"> Не выполнено условие присутствия (отсутствия) элемента ФИО при наличии элемента ИННФЛ в количестве, равном "<usch:value-of select="count(@ИННФЛ)"/>" и при наличии элемента ИныеСвед в количестве, равном "<usch:value-of select="count(@ИныеСвед)"/>". </usch:error>
											</sch:assert>
										</sch:rule>
									</sch:pattern>
								</xs:appinfo>
								<!---*************************************************************************************************************************************************************-->
								<!---*************************************************************************************************************************************************************-->
								<xs:appinfo>
									<sch:pattern name="Наличие элемента ИныеСвед в зависимости от наличия элемента ФИО">
										<sch:rule context="СвФЛУч">
											<sch:assert test="usch:iif( 
						count(ФИО)=0  ,
						count(@ИныеСвед)!=0  , 
						( count(@ИныеСвед)!=0  or  count@ИныеСвед)=0 ) 
						)">
												<usch:error code="0400400007" path="@ИныеСвед" value-of-select="count(@ИныеСвед)"> Не выполнено условие присутствия (отсутствия) элемента @ИныеСвед при наличии элемента ФИО в количестве, равном "<usch:value-of select="count(ФИО)"/>". </usch:error>
											</sch:assert>
										</sch:rule>
									</sch:pattern>
								</xs:appinfo>
								<!---*************************************************************************************************************************************************************-->
								<xs:documentation>Сведения о физическом лице, не являющемся индивидуальным предпринимателем</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="ФИО" type="ФИОТип" minOccurs="0">
										<xs:annotation>
											<xs:documentation>Фамилия, имя, отчество (при наличии)</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="ИННФЛ" type="ИННФЛТип" use="optional">
									<xs:annotation>
										<xs:documentation>ИНН физического лица</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="ИныеСвед" use="optional">
									<xs:annotation>
										<xs:documentation>Иные сведения, в том числе сведения, идентифицирующие физическое лицо</xs:documentation>
									</xs:annotation>
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:minLength value="1"/>
											<xs:maxLength value="255"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element name="Адрес" type="АдресТип">
				<xs:annotation>
					<xs:documentation>Адрес</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="БанкРекв" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Банковские реквизиты</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="СвБанк" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Сведения о банке</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:attribute name="НаимБанк" use="optional">
									<xs:annotation>
										<xs:documentation>Наименование банка</xs:documentation>
									</xs:annotation>
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:minLength value="1"/>
											<xs:maxLength value="1000"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="БИК" type="БИКТип" use="optional">
									<xs:annotation>
										<xs:documentation>Банковский идентификационный код (БИК)</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="КорСчет" use="optional">
									<xs:annotation>
										<xs:documentation>Корреспондентский счет банка</xs:documentation>
									</xs:annotation>
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:minLength value="1"/>
											<xs:maxLength value="20"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="НомерСчета" use="optional">
						<xs:annotation>
							<xs:documentation>Номер банковского счета</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:minLength value="1"/>
								<xs:maxLength value="20"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="Контакт" type="КонтактТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Контактные данные</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="ОКПО" type="ОКПОТип" use="optional">
			<xs:annotation>
				<xs:documentation>Код по Общероссийскому классификатору предприятий и организаций</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="КодОПФ" type="ОКОПФТип" use="optional">
			<xs:annotation>
				<xs:documentation>Код по Общероссийскому классификатору организационно-правовых форм</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="ПолнНаимОПФ" use="optional">
			<xs:annotation>
				<xs:documentation>Полное наименование организационно-правовой формы</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="4"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="СтруктПодр" use="optional">
			<xs:annotation>
				<xs:documentation>Структурное подразделение</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="500"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ИнфДляУчаст" use="optional">
			<xs:annotation>
				<xs:documentation>Информация для участника документооборота</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="СокрНаим" use="optional">
			<xs:annotation>
				<xs:documentation>Сокращенное наименование</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="510"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="СвИнНеУчТип">
		<xs:annotation>
			<xs:documentation>Сведения об иностранной организации (иностранном гражданине), не состоящей/состоящем на учете в налоговом органе</xs:documentation>
		</xs:annotation>
		<xs:attribute name="ИдСтат" use="required">
			<xs:annotation>
				<xs:documentation>Идентификация статуса</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:length value="2"/>
					<xs:enumeration value="ИО"/>
					<xs:enumeration value="ИГ"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="КодСтр" type="ОКСМТип" use="required">
			<xs:annotation>
				<xs:documentation>Код страны</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="НаимСтран" use="required">
			<xs:annotation>
				<xs:documentation>Наименование страны</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Наим" use="required">
			<xs:annotation>
				<xs:documentation>Наименование иностранной организации полное/фамилия, имя, отчество (при наличии) иностранного гражданина</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="1000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Идентиф" use="optional">
			<xs:annotation>
				<xs:documentation>Идентификатор иностранной организации (иностранного гражданина)</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ИныеСвед" use="optional">
			<xs:annotation>
				<xs:documentation>Иные сведения для однозначной идентификации иностранной организации (иностранного гражданина)</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ПортТип">
		<xs:annotation>
			<xs:documentation>Сведения о порте</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="КоордПор" type="КоордТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Координаты места нахождения порта</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Адрес" type="АдресТип">
				<xs:annotation>
					<xs:documentation>Сведения об адресе местонахождения</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="НаимПорт" use="required">
			<xs:annotation>
				<xs:documentation>Наименование порта</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Терминал" use="optional">
			<xs:annotation>
				<xs:documentation>Терминал порта</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="КоордТип">
		<xs:annotation>
			<xs:documentation>Координаты места</xs:documentation>
		</xs:annotation>
		<xs:attribute name="Широта" use="required">
			<xs:annotation>
				<xs:documentation>Широта </xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="15"/>
					<xs:maxLength value="17"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Долгота" use="required">
			<xs:annotation>
				<xs:documentation>Долгота</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="15"/>
					<xs:maxLength value="18"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="АдрРФТип">
		<xs:annotation>
			<xs:documentation>Сведения об адресе в Российской Федерации, содержащиеся в ЕГРЮЛ</xs:documentation>
		</xs:annotation>
		<xs:attribute name="Индекс" use="optional">
			<xs:annotation>
				<xs:documentation>Почтовый индекс</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:length value="6"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="КодРегион" type="СCРФТип" use="required">
			<xs:annotation>
				<xs:documentation>Код субъекта Российской Федерации</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="НаимРегион" use="required">
			<xs:annotation>
				<xs:documentation>Наименование субъекта Российской Федерации</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="51"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Район" use="optional">
			<xs:annotation>
				<xs:documentation>Район</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Город" use="optional">
			<xs:annotation>
				<xs:documentation>Город</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="НаселПункт" use="optional">
			<xs:annotation>
				<xs:documentation>Населенный пункт</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Улица" use="optional">
			<xs:annotation>
				<xs:documentation>Улица</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Дом" use="optional">
			<xs:annotation>
				<xs:documentation>Дом</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Корпус" use="optional">
			<xs:annotation>
				<xs:documentation>Корпус</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Кварт" use="optional">
			<xs:annotation>
				<xs:documentation>Квартира</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ИныеСвед" use="optional">
			<xs:annotation>
				<xs:documentation>Иные сведения об адресе в Российской Федерации</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="1000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="АдрИнфТип">
		<xs:annotation>
			<xs:documentation>Информация об адресе, в том числе за пределами территории Российской Федерации</xs:documentation>
		</xs:annotation>
		<xs:attribute name="КодСтр" type="ОКСМТип" use="required">
			<xs:annotation>
				<xs:documentation>Код страны</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="НаимСтран" use="required">
			<xs:annotation>
				<xs:documentation>Наименование страны</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="АдрТекст" use="required">
			<xs:annotation>
				<xs:documentation>Адрес</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="1000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="АдресТип">
		<xs:annotation>
			<xs:documentation>Сведения об адресе (месте нахождения)</xs:documentation>
		</xs:annotation>
		<xs:choice>
			<xs:element name="АдрРФ" type="АдрРФТип">
				<xs:annotation>
					<xs:documentation>Адрес, указанный в Едином государственном реестре юридических лиц/почтовый адрес/адрес регистрации по месту жительства индивидуального предпринимателя, указанный в Едином государственном реестре индивидуальных предпринимателей (реквизиты адреса на территории Российской Федерации)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="АдрГАР" type="АдрГАРТип">
				<xs:annotation>
					<!---**************************************************************************************************************************************************************************-->
					<xs:appinfo>
						<sch:pattern name="Проверка присутствия (отсутствия) элемента МуниципРайон в зависимости от значения элемента Регион">
							<sch:rule context="АдрГАР">
								<sch:assert test="usch:iif(
								Регион=99, 
								count(МуниципРайон)=0, 
								count(МуниципРайон)!=0
								)">
									<usch:error code="0400300003" path="МуниципРайон" value-of-select="Регион">Не выполнено условие присутствия (отсутствия) элемента МуниципРайон при значении элемента Регион, равном "<usch:value-of select="Регион"/>" </usch:error>
								</sch:assert>
							</sch:rule>
						</sch:pattern>
					</xs:appinfo>
					<!---**************************************************************************************************************************************************************************-->
					<xs:documentation>Адрес в соответствии с государственным адресным реестром, указанный в Едином государственном реестре юридических лиц/почтовый адрес/адрес регистрации по месту жительства индивидуального предпринимателя, указанный в Едином государственном реестре индивидуальных предпринимателей (реквизиты адреса на территории Российской Федерации)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="АдрИнф" type="АдрИнфТип">
				<xs:annotation>
					<xs:documentation>Адрес, указанный в Едином государственном реестре юридических лиц/почтовый адрес/адрес регистрации по месту жительства индивидуального предпринимателя, указанный в Едином государственном реестре индивидуальных предпринимателей (информация об адресе, в том числе об адресе за пределами территории Российской Федерации)</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:choice>
		<xs:attribute name="ГЛНМеста" use="optional">
			<xs:annotation>
				<xs:documentation>Глобальный номер места нахождения (GLN места)</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:length value="13"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="АдрГАРТип">
		<xs:annotation>
			<xs:documentation>Адрес в соответствии с государственным адресным реестром</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Регион" type="СCРФТип">
				<xs:annotation>
					<xs:documentation>Субъект Российской Федерации (код)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="НаимРегион">
				<xs:annotation>
					<xs:documentation>Наименование субъекта Российской Федерации</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="51"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="МуниципРайон" type="ВидНаимКодТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Муниципальный район/городской округ/внутригородская территория города федерального значения/муниципальный округ/федеральная территория</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ГородСелПоселен" type="ВидНаимКодТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Городское поселение/сельское поселение/межселенная территория в составе муниципального района/внутригородской район городского округа</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="НаселенПункт" type="ВидНаимТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Населенный пункт (город, деревня, село и прочее)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ЭлПланСтруктур" type="ТипНаимТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Элемент планировочной структуры</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ЭлУлДорСети" type="ТипНаимТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Элемент улично-дорожной сети</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ЗемелУчасток" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Земельный участок (номер)</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="50"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Здание" type="НомерТип" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Здание/строение/сооружение/объект незавершенного строительства</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ПомещЗдания" type="НомерТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Помещение в пределах здания/строения/сооружения/машино-место</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ПомещКвартиры" type="НомерТип" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Помещение в пределах квартиры</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="ИдНом" use="required">
			<xs:annotation>
				<xs:documentation>Уникальный номер адреса объекта адресации в государственном адресном реестре</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:length value="36"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Индекс" use="optional">
			<xs:annotation>
				<xs:documentation>Почтовый индекс</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:length value="6"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ВидНаимКодТип">
		<xs:annotation>
			<xs:documentation>Сведения о виде (код) и наименовании адресного элемента</xs:documentation>
		</xs:annotation>
		<xs:attribute name="ВидКод" use="required">
			<xs:annotation>
				<xs:documentation>Вид (код) элемента</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:length value="1"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Наим" use="required">
			<xs:annotation>
				<xs:documentation>Наименование элемента</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ВидНаимТип">
		<xs:annotation>
			<xs:documentation>Сведения о виде и наименовании адресного элемента</xs:documentation>
		</xs:annotation>
		<xs:attribute name="Вид" use="required">
			<xs:annotation>
				<xs:documentation>Вид элемента</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Наим" use="required">
			<xs:annotation>
				<xs:documentation>Наименование элемента</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ТипНаимТип">
		<xs:annotation>
			<xs:documentation>Сведения о типе и наименовании адресного элемента</xs:documentation>
		</xs:annotation>
		<xs:attribute name="Тип" use="required">
			<xs:annotation>
				<xs:documentation>Тип элемента</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Наим" use="required">
			<xs:annotation>
				<xs:documentation>Наименование элемента</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="НомерТип">
		<xs:annotation>
			<xs:documentation>Сведения о номере адресного элемента</xs:documentation>
		</xs:annotation>
		<xs:attribute name="Тип" use="required">
			<xs:annotation>
				<xs:documentation>Тип элемента</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Номер" use="required">
			<xs:annotation>
				<xs:documentation>Номер элемента</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="КонтактТип">
		<xs:annotation>
			<xs:documentation>Контактные данные</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Тлф" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Номер контактного телефона/факс</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ЭлПочта" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Адрес электронной почты</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ИнКонт" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Иные контактные данные</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ИнфПолТип">
		<xs:annotation>
			<xs:documentation>Информационное поле</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="ТекстИнф" type="ТекстИнфТип" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Текстовая информация</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="ИдФайлИнфПол" use="optional">
			<xs:annotation>
				<xs:documentation>Идентификатор файла информационного поля</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:length value="36"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ТекстИнфТип">
		<xs:annotation>
			<xs:documentation>Текстовая информация</xs:documentation>
		</xs:annotation>
		<xs:attribute name="Идентиф" use="required">
			<xs:annotation>
				<xs:documentation>Идентификатор</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Значен" use="required">
			<xs:annotation>
				<xs:documentation>Значение</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="2000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ПодписантТип">
		<xs:annotation>
			<xs:documentation>Сведения о лице, подписывающем информацию отправителя в электронной форме</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="ФИО" type="ФИОТип">
				<xs:annotation>
					<xs:documentation>Фамилия, имя, отчество (при наличии)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:choice>
				<xs:element name="СвДоверЭл" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Сведения о доверенности в электронной форме в машиночитаемом виде, используемой для подтверждения полномочий представителя</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="НомДовер" use="required">
							<xs:annotation>
								<xs:documentation>Единый регистрационный номер доверенности</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:length value="36"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="ДатаВыдДовер" type="ДатаТип" use="required">
							<xs:annotation>
								<xs:documentation>Дата совершения (выдачи) доверенности</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="ВнНомДовер" use="optional">
							<xs:annotation>
								<xs:documentation>Внутренний номер доверенности</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="1"/>
									<xs:maxLength value="50"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="ДатаВнРегДовер" type="ДатаТип" use="optional">
							<xs:annotation>
								<xs:documentation>Дата внутренней регистрации доверенности</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="ИдСистХран" use="required">
							<xs:annotation>
								<xs:documentation>Идентифицирующая информация об информационной системе, в которой осуществляется хранение доверенности, необходимая для запроса информации из такой информационной системы</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="1"/>
									<xs:maxLength value="500"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="УРЛСист" use="optional">
							<xs:annotation>
								<xs:documentation>Сведения в формате URL об информационной системе, которая предоставляет техническую возможность получения информации о доверенности</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="1"/>
									<xs:maxLength value="500"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="СвДоверБум" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Сведения о доверенности в форме документа на бумажном носителе, используемой для подтверждения полномочий представителя</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ФИО" type="ФИОТип" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Фамилия, имя, отчество (при наличии) лица, подписавшего доверенность</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="ДатаВыдДовер" type="ДатаТип" use="required">
							<xs:annotation>
								<xs:documentation>Дата совершения (выдачи) доверенности</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="ВнНомДовер" use="required">
							<xs:annotation>
								<xs:documentation>Внутренний номер доверенности</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="1"/>
									<xs:maxLength value="50"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="СвИдДовер" use="optional">
							<xs:annotation>
								<xs:documentation>Сведения, идентифицирующие доверителя</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="1"/>
									<xs:maxLength value="1000"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="Должн" use="required">
			<xs:annotation>
				<xs:documentation>Должность</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ТипПодпис" use="optional">
			<xs:annotation>
				<xs:documentation>Тип подписи</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:length value="1"/>
					<xs:enumeration value="1"/>
					<xs:enumeration value="2"/>
					<xs:enumeration value="3"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ДатаПодДок" type="ДатаТип" use="optional">
			<xs:annotation>
				<xs:documentation>Дата подписания документа</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="СпосПодтПолном" use="required">
			<xs:annotation>
				<xs:documentation>Способ подтверждения полномочий на подписание документа</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:length value="1"/>
					<xs:enumeration value="1"/>
					<xs:enumeration value="2"/>
					<xs:enumeration value="3"/>
					<xs:enumeration value="4"/>
					<xs:enumeration value="5"/>
					<xs:enumeration value="6"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ДопСведПодп" use="optional">
			<xs:annotation>
				<xs:documentation>Дополнительные сведения</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ФИОТип">
		<xs:annotation>
			<xs:documentation>Фамилия, имя, отчество физического лица</xs:documentation>
		</xs:annotation>
		<xs:attribute name="Фамилия" use="required">
			<xs:annotation>
				<xs:documentation>Фамилия</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="60"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Имя" use="required">
			<xs:annotation>
				<xs:documentation>Имя</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="60"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Отчество" use="optional">
			<xs:annotation>
				<xs:documentation>Отчество</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="60"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="ИННФЛТип">
		<xs:annotation>
			<xs:documentation>Идентификационный номер налогоплательщика - физического лица</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="12"/>
			<xs:pattern value="([0-9]{1}[1-9]{1}|[1-9]{1}[0-9]{1})[0-9]{10}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ИННЮЛТип">
		<xs:annotation>
			<xs:documentation>Идентификационный номер налогоплательщика - организации</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="10"/>
			<xs:pattern value="([0-9]{1}[1-9]{1}|[1-9]{1}[0-9]{1})[0-9]{8}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="КППТип">
		<xs:annotation>
			<xs:documentation>Код причины постановки на учет (КПП) - 5 и 6 знаки от 0-9 и A-Z</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="9"/>
			<xs:pattern value="([0-9]{1}[1-9]{1}|[1-9]{1}[0-9]{1})([0-9]{2})([0-9A-Z]{2})([0-9]{3})"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="КНДТип">
		<xs:annotation>
			<xs:documentation>Код из Классификатора налоговой документации</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="7"/>
			<xs:pattern value="[0-9]{7}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="БИКТип">
		<xs:annotation>
			<xs:documentation>БИК банка</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="9"/>
			<xs:pattern value="[0-9]{9}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ОГРНИПТип">
		<xs:annotation>
			<xs:documentation>Основной государственный регистрационный номер индивидуального предпринимателя</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="15"/>
			<xs:pattern value="[0-9]{15}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="СCРФТип">
		<xs:annotation>
			<xs:documentation>Код из Справочника субъектов Российской Федерации </xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="2"/>
			<xs:pattern value="[0-9]{2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ОКВТип">
		<xs:annotation>
			<xs:documentation>Код из Общероссийского классификатора валют</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="3"/>
			<xs:pattern value="[0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ОКСМТип">
		<xs:annotation>
			<xs:documentation>Код из Общероссийского классификатора стран мира</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="3"/>
			<xs:pattern value="[0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ОКОПФТип">
		<xs:annotation>
			<xs:documentation>Код из Общероссийского классификатора организационно-правовых форм хозяйствующих субъектов</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="2"/>
			<xs:maxLength value="5"/>
			<xs:pattern value="[0-9]{2}"/>
			<xs:pattern value="[0-9]{5}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ОКПОТип">
		<xs:annotation>
			<xs:documentation>Код из Общероссийского классификатора предприятий и организаций</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ОКВГУМТип">
		<xs:annotation>
			<xs:documentation>Код из Общероссийского классификатора видов груза, упаковки и упаковочных материалов (ОКВГУМ)</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="2"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ВремяТип">
		<xs:annotation>
			<xs:documentation>Время в формате ЧЧ:ММ:СС</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="8"/>
			<xs:pattern value="([0-1]{1}[0-9]{1}|2[0-3]{1}):([0-5]{1}[0-9]{1}):([0-5]{1}[0-9]{1})"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ДатаТип">
		<xs:annotation>
			<xs:documentation>Дата в формате ДД.ММ.ГГГГ (01.01.1900 - 31.12.2099)</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="10"/>
			<xs:pattern value="(((0[1-9]{1}|[1-2]{1}[0-9]{1})\.(0[1-9]{1}|1[0-2]{1}))|((30)\.(01|0[3-9]{1}|1[0-2]{1}))|((31)\.(01|03|05|07|08|10|12)))\.(19[0-9]{2}|20[0-9]{2})"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ДатаВремяВЗТип">
		<xs:annotation>
			<xs:documentation>Дата и время в формате ДД.ММ.ГГГГTЧЧ:ММ:CC+-ЧЧ:ММ</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="25"/>
			<xs:pattern value="(((((0[1-9]{1}|1[0-9]{1}|2[0-8]{1})\.(0[1-9]{1}|1[0-2]{1}))|((29|30)\.(01|0[3-9]{1}|1[0-2]{1}))|(31\.(01|03|05|07|08|10|12)))\.((19|20)[0-9]{2}))|(29\.02\.((19|20)(((0|2|4|6|8)(0|4|8))|((1|3|5|7|9)(2|6))))))([T]([0-1]{1}[0-9]{1}|2[0-3]{1}):([0-5]{1}[0-9]{1}):([0-5]{1}[0-9]{1})([+|-]([01][0-9])[:]([0-5][0-9])))"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
